-- 005f: private wishlist item snapshot Storage bucket and owner-only policies.
--
-- Forward-only migration implementing the binding brief
-- docs/delivery/issues/005f-extraction-review-and-manual-fallback.md
-- (slice 20, Linear ARJ-31). Never edit this file once applied anywhere;
-- fix forward with a new migration (see supabase/README.md).
--
-- Guarantees:
--   * The bucket is PRIVATE (public = false): objects are reachable only
--     through short-expiry signed URLs generated by server code for the
--     owner, never through a public URL.
--   * The 2 MiB file_size_limit matches 005e's normalized-output cap and
--     the single image/webp allowed MIME matches its re-encoding contract:
--     only bounded, metadata-free, re-encoded WebP snapshots ever enter
--     the bucket.
--   * Owner-only access: each of the four policies requires the object's
--     first path folder (storage.foldername(name)[1]) to equal the
--     caller's auth.uid()::text under bucket_id = 'wishlist-item-snapshots'.
--     Objects live under {owner_id}/{client_submission_id}.webp, so an
--     authenticated user can only ever reach their own prefix. No anon
--     policy and no service-role policy is added (service_role bypasses
--     RLS by its role bypass attribute; no application path uses it).
--   * No wishlist_items schema, grant, or policy changes here: the 005c
--     create boundary and append_wishlist_item RPC are consumed unmodified,
--     and image/extraction columns are written after create through the
--     existing 005a owner-scoped UPDATE grant.
--
-- Rollback: drop the four policies, then delete the bucket ONLY after a
-- decision on retained objects (objects are content the owner chose to
-- keep; dropping them destroys data). The UI degrades to the
-- image_url/branded-placeholder fallback while rows still reference paths.

-- Idempotent bucket upsert: re-running the migration converges on the
-- pinned configuration instead of failing on the existing row.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'wishlist-item-snapshots',
  'wishlist-item-snapshots',
  false,
  2097152,
  array['image/webp']
)
on conflict (id) do update set
  public = false,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Symmetric drop-if-exists guards keep the policy statements idempotent.
drop policy if exists wishlist_item_snapshots_select_own on storage.objects;
drop policy if exists wishlist_item_snapshots_insert_own on storage.objects;
drop policy if exists wishlist_item_snapshots_update_own on storage.objects;
drop policy if exists wishlist_item_snapshots_delete_own on storage.objects;

create policy wishlist_item_snapshots_select_own on storage.objects
  for select
  to authenticated
  using (
    bucket_id = 'wishlist-item-snapshots'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy wishlist_item_snapshots_insert_own on storage.objects
  for insert
  to authenticated
  with check (
    bucket_id = 'wishlist-item-snapshots'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy wishlist_item_snapshots_update_own on storage.objects
  for update
  to authenticated
  using (
    bucket_id = 'wishlist-item-snapshots'
    and (storage.foldername(name))[1] = auth.uid()::text
  )
  with check (
    bucket_id = 'wishlist-item-snapshots'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy wishlist_item_snapshots_delete_own on storage.objects
  for delete
  to authenticated
  using (
    bucket_id = 'wishlist-item-snapshots'
    and (storage.foldername(name))[1] = auth.uid()::text
  );
